layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    - mathviz
    - delta2tex
    - math-editor-example
    - rich-formatting-jupyter
    - quick-eval
    - data-science-tools
    - vscode-datascience-extensions
    

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: samuel-helms-bb0b68b5
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  # - name: CSS
  #   web_url: https://github.com/topics/css
  #   image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Representation learning
    image_url: ./lda.png
    web_url: https://github.com/samghelms/similar_eqs_senior_proj/blob/master/report/writeup.pdf

  - name: Application design
    image_url: ./electron.png
    web_url: https://github.com/samghelms/data-science-tools

  - name: Data visualization
    image_url: ./tsne.png
    web_url: https://samghelms.github.io/webgl-scatter/

  - name: Probabilistic programming/Bayesian statistics
    image_url: ./pp.png

  - name: Time series forecasting
    image_url: ./ts.png